import turtle
turtle.left(90)
turtle.forward(100)
turtle.goto(50,50)
turtle.goto(100,100)
turtle.back(100)
turtle.right(90)
turtle.penup()
turtle.forward(70)
turtle.pendown()
turtle.forward(80)
turtle.penup()
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.pendown()
turtle.forward(80)
turtle.right(90)
turtle.penup()
turtle.forward(50)
turtle.right(90)
turtle.pendown()
turtle.forward(80)
turtle.back(80)
turtle.left(-90)
turtle.forward(100)
turtle.left(90)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.forward(80)
turtle.penup()
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.pendown()
turtle.forward(80)
turtle.right(90)
turtle.penup()
turtle.forward(50)
turtle.right(90)
turtle.pendown()
turtle.forward(80)
turtle.back(80)
turtle.left(-90)
turtle.forward(100)







turtle.mainloop()
